### ISSUE TITLE
在commands中使用Amazon数据集的问题

### ISSUE THREAD

**Issue by Je5s1e** [mikudehuane/MPDA#2]
我下载了Amazon数据集，然后按README.md中对Amazon数据集的处理教程全都成功执行，并且在Amazon数据集下生成了预处理目录/processed。然而，当我执行commands/amazon_lr_m-100.sh的时候，会报错，提示Amazon数据集预处理目录/processed下缺失文件item2category.csv，不确定是否是对Amazon数据集预处理过程中存在什么问题。作为对比，我使用movielens数据集执行这些bash训练的时候都能成功执行。报错提示如下：
<img width="1017" alt="817ED68519F0435F9C4390D422E45231" src="https://github.com/user-attachments/assets/2b7dd817-63cd-403a-9205-a901dd6932f0">

**Comment by mikudehuane** [comment]
Run scripts/preprocess/amazon/extract_meta.py may help
